name: server-test

services:
  db:
    image: mysql
    env_file:
      - .env
    volumes:
      - ./.test-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 2s
      retries: 10

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    command: ["go", "test", "-v", "./..."]
    